### ISSUE TITLE
C64 TCP gateway

### ISSUE THREAD

**Issue by donpdonp** [marioballano/emudore#1]
I started the emulator and it worked out of the box. The first thing I thought to do is run some kind of TCP client and IRC would be fun to see on the C64. 

This is a C64 IRC client
http://contiki.cbm8bit.com/

Its options for networking are "RR+RR-NET" "TFE" and "ETH64". If you know what these are (I don't), is it possible to support one of them?

**Comment by marioballano** [comment]
Thanks for testing and giving some feedback!!

Those ethernet adapters are accessories for the C64 that connect to the cartridge port:

http://wiki.icomp.de/wiki/RR-Net

It'd be interesting to emulate one of these in the future, I have marked this issue as an enhancement, in the meantime, if you wish to test the IRC client I encourage you to give the vice emulator a go (it's one of the most complete C64 emulators and it apparently supports RR-NET already):

http://vice-emu.sourceforge.net/
https://www.commodoreserver.com/BlogEntryView.asp?EID=CDB68A9028654CCEA758D37C6DB3E05B
