### ISSUE TITLE
Question, RAM bug?

### ISSUE THREAD

**Issue by xlar54** [marioballano/emudore#13]
Hey Mario,

One question I have for you - dont know if its my implementation or if you can replicate it in your code.  If I patch RAM such as:

mem_ram_[0xc000] = 0xff;

It will place that value just fine.  But if I try to POKE a new value into that memory location, it treats it like a ROM and wont overwrite those values.  Seems to happen anywhere I set RAM. 

Could you try this and see if you get the same problem?
 
![ram patch](https://user-images.githubusercontent.com/1909642/33241428-b33b7820-d28a-11e7-82e0-53bea5a1c05d.PNG)

**Comment by marioballano** [comment]
uhm.. seems to work fine in my implementation, it might have something to do with memory banking?
<img width="803" alt="screen shot 2017-11-26 at 18 09 36" src="https://user-images.githubusercontent.com/3779058/33242419-0d8ef0aa-d2d5-11e7-8bef-4234ff1ad03d.png">

**Comment by marioballano** [comment]
I have just tested setting the value to 0xff  within the Memory class constructor, peek() reads the right value and poke seems to overwrite it just fine

**Comment by xlar54** [comment]
ok cool, thank you.  Ill see what Im doing wrong.  Appreciate the double check!

**Comment by marioballano** [comment]
no problem :), see if you can add some debug code around Memory::read_byte and Memory::write_byte, maybe memory banking is screwing things up.. IIRC even in the actual C64 you could effectively write values to the underlying RAM but reading would yield the ROM values due to the memory banking config.

**Comment by xlar54** [comment]
I figured it out, thanks!  I was patching ROM inside a call to your setup_memory_banks() function.  Works fine for ROM, but I added a RAM patch in there also, and due to the banking, you were 100% right.  I extracted a patch_ram() function and it works perfectly.  Thanks again.  (In my case, I have an ML monitor that I want available to me while Im working on the OS, and so patching RAM is needed).

**Comment by marioballano** [comment]
great!, I remember I went across similar issues when I first wrote the memory banking support that's why it sounded familiar :)
