### ISSUE TITLE
38/40 col mode fix

### ISSUE THREAD

**Issue by xlar54** [marioballano/emudore#6]
Control register 53270, bit 3 handles 38 or 40 column mode.   POKE53270,0 should make it go 38 column and POKE53270,8 should return to normal.

Here's a patch you can apply to provide this function:

`void Vic::draw_raster_char_mode()
{
  int rstr = raster_counter();
  int y = rstr - kFirstVisibleLine;
  if((rstr >= kGFirstLine) && (rstr < kGLastLine) && !is_screen_off())
  {
    /* draw background */
    if(!ISSET_BIT(cr2_,3)) // 38 columns
      io_->screen_draw_rect(kGFirstCol+8,y,kGResX-16,bgcolor_[0]);
    else
      io_->screen_draw_rect(kGFirstCol,y,kGResX,bgcolor_[0]);

    /* draw characters */
    for(int column=0; column < kGCols ; column++)
    {
      if(!ISSET_BIT(cr2_,3)) // 38 columns
      {
	if(column == 0) continue;
	if(column == kGCols-1) continue;
      }
    
      int x = kGFirstCol + column * 8;
      int line = rstr - kGFirstLine;
      int row = line/8;
      int char_row = line % 8;
      /* retrieve screen character */
      uint8_t c = get_screen_char(column,row);
      /* retrieve character bitmap data */
      uint8_t data = get_char_data(c,char_row);
      /* retrieve color data */
      uint8_t color  = get_char_color(column,row);
      /* draw character */
      if(graphic_mode_ == kMCCharMode && ISSET_BIT(color,3))
        draw_mcchar(x,y,data,(color&0x7));
      else
        draw_char(x,y,data,color);
    }
  }
}
`

**Comment by marioballano** [comment]
thanks for pointing this out Scott!, I just applied your patch and tested and it does indeed seem to work fine :D

**Comment by xlar54** [comment]
No problem.  Im running a bunch of test programs through the operating system and as I run into more patches, Ill send them your way.

Sent from Mail for Windows 10
